APP_NAME: "account-consumer-service"
SERVER_HOST: "0.0.0.0:1004"
HEALTH_SERVER_HOST: "0.0.0.0:1005"

DATABASE_USER: "cassandra"
DATEBASE_PASSWORD: "cassandra"
DATEBASE_KEYSPACE: "account_consumer_service"
DATEBASE_HOST: "localhost"
DATEBASE_PORT: 9042
DATEBASE_CONNECTION_RETRY_TIME: 5
DATEBASE_RETRY_MIN: 1
DATEBASE_RETRY_MAX: 10
DATEBASE_NUM_RETRIES: 5
DATEBASE_CLUSTER_TIMEOUT: 5

KAFKA_CLIENT_ID: "account-consumer-service"    
KAFKA_HOSTS: "localhost:9092"
KAFKA_USE_AUTHENTICATION: "false"  
KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
KAFKA_ENABLE_TLS: "true"
KAFKA_SCHEMA_REGISTRY_HOST: "http://localhost:8086"
KAFKA_QLD_TOPIC_NAME: account_createorupdate_dlq account_delete_dlq
KAFKA_CONSUMER_TOPIC_NAME: account_createorupdate account_delete
KAFKA_CONSUMER_GROUP: "account-service"