APP_NAME: "account-consumer-service"
SERVER_HOST: "0.0.0.0:8080"
HEALTH_SERVER_HOST: "0.0.0.0:8081"

DATABASE_USER: "cassandra"
DATEBASE_PASSWORD: "cassandra"
DATEBASE_KEYSPACE: "account"
DATEBASE_HOST: "localhost"
DATEBASE_PORT: 9042
DATEBASE_CONNECTION_RETRY_TIME: 5
DATEBASE_RETRY_MIN: 1
DATEBASE_RETRY_MAX: 10
DATEBASE_NUM_RETRIES: 5
DATEBASE_CLUSTER_TIMEOUT: 5

KAFKA_HAS_AUTH: false
KAFKA_TIMEOUT: 30
KAFKA_CLIENT_ID: "account-consumer-service"
KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
KAFKA_USER: "kafka"
KAFKA_PASSWORD: "kafka"
KAFKA_ADDRESS: "localhost:9092"
KAFKA_SCHEMA_REGISTRY_HOST: "http://localhost:8085"
KAFKA_SCHEMA_REGISTRY_USER: "kafka"
KAFKA_SCHEMA_REGISTRY_PASSWORD: "kafka"
KAFKA_ENABLE_EVENTS: true